rpc-stream:
	protoc --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		routeguide/route_guide.proto\

static:
       zig build-lib -fno-stage1 -femit-h zgo.zig
       go build -ldflags "-linkmode external -extldflags -static" bridge.go

dynamic:
       zig build-lib -dynamic -fno-stage1 -femit-h zgo.zig
       go build -ldflags "-linkmode external -extldflags -dynamic" bridge.go